export const metadata = {
  title: 'Disclaimer — Signet AI',
  description: 'Signet AI Legal Disclaimer — contract analysis is not formal legal advice.'
}

const h2Style = { fontSize: 20, color: '#FFFFFF', fontWeight: 600 as const, marginTop: 40, marginBottom: 12, paddingTop: 24, borderTop: '1px solid rgba(255,255,255,0.06)' }

export default function DisclaimerPage() {
  return (
    <section style={{ background: '#0D1B2A', padding: '120px 24px 96px' }}>
      <div style={{ maxWidth: 740, margin: '0 auto', fontSize: 15, color: 'rgba(255,255,255,0.72)', lineHeight: 1.8 }}>
        <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 42, color: '#FFFFFF', fontWeight: 400, marginBottom: 36, lineHeight: 1.2 }}>Legal Disclaimer</h1>
        <p><strong style={{ color: 'rgba(255,255,255,0.85)' }}>Last updated: May 2026</strong></p>
        <p>Please read this Legal Disclaimer carefully before using Signet AI ("the Platform", "the Service"). By accessing or using the Platform, you acknowledge that you understand and agree to the terms below.</p>

        <h2 style={h2Style}>Not Legal Advice</h2>
        <p>Signet AI is an AI-powered contract analysis tool. All analyses, summaries, risk scores, and recommendations generated by the Platform are for educational and informational purposes only. Nothing on our Platform constitutes formal legal advice, nor does it establish an attorney-client relationship.</p>

        <h2 style={h2Style}>No Guarantee of Accuracy</h2>
        <p>Contract law is highly nuanced, context-dependent, and subject to jurisdictional variation. While our Gemini-powered risk detection engine is advanced, it may occasionally fail to identify specific risks or mischaracterize clause clauses. Signet AI makes no guarantees regarding the legal enforceability or completeness of its reports.</p>

        <h2 style={h2Style}>Consult an Advocate</h2>
        <p>You should never sign a high-value commercial contract solely based on Signet AI analysis. We strongly recommend connecting with a licensed advocate (such as the independent corporate lawyers in our partner network) to review your drafts before execution.</p>

        <h2 style={h2Style}>Limitation of Liability</h2>
        <p>Under no circumstances shall Signet AI, its parent company, or its developers be held liable for any direct, indirect, incidental, or consequential damages resulting from your reliance on Platform-generated reports or our advocate referral matches.</p>
      </div>
    </section>
  )
}
