import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font, pdf } from '@react-pdf/renderer';

// Register fonts if needed, otherwise rely on standard ones.
// In react-pdf standard fonts include Helvetica, Times-Roman, Courier
Font.register({
  family: 'Open Sans',
  fonts: [
    { src: 'https://cdn.jsdelivr.net/npm/open-sans-all@0.1.3/fonts/open-sans-regular.ttf' },
    { src: 'https://cdn.jsdelivr.net/npm/open-sans-all@0.1.3/fonts/open-sans-700.ttf', fontWeight: 700 }
  ]
});

const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontFamily: 'Open Sans',
    backgroundColor: '#FFFFFF',
  },
  header: {
    marginBottom: 20,
    borderBottom: '2pt solid #0F172A',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 700,
    color: '#0F172A',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: '#475569',
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 700,
    color: '#0F172A',
    marginBottom: 12,
  },
  card: {
    border: '1pt solid #E2E8F0',
    borderRadius: 8,
    padding: 16,
    marginBottom: 16,
    flexWrap: 'wrap',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
    borderBottom: '1pt solid #F1F5F9',
    paddingBottom: 8,
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  clauseTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: '#0F172A',
    width: '70%',
  },
  riskBadge: {
    padding: '4px 8px',
    borderRadius: 4,
    border: '1pt solid #E2E8F0',
  },
  riskBadgeText: {
    fontSize: 9,
    fontWeight: 700,
  },
  originalTextHeader: {
    fontSize: 10,
    fontWeight: 700,
    color: '#64748B',
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  originalText: {
    fontSize: 10,
    fontFamily: 'Courier',
    backgroundColor: '#F8FAFC',
    padding: 10,
    borderRadius: 4,
    marginBottom: 12,
    color: '#334155',
  },
  plainEnglishHeader: {
    fontSize: 10,
    fontWeight: 700,
    color: '#059669',
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  plainEnglish: {
    fontSize: 12,
    color: '#334155',
    marginBottom: 12,
  },
  playbookViolation: {
    backgroundColor: '#FEF2F2',
    borderLeft: '4pt solid #EF4444',
    padding: 8,
    marginBottom: 12,
  },
  playbookText: {
    color: '#B91C1C',
    fontSize: 12,
    fontWeight: 700,
  },
  summaryBox: {
    backgroundColor: '#F8FAFC',
    padding: 16,
    borderRadius: 8,
    border: '1pt solid #E2E8F0',
    marginBottom: 20,
  },
  summaryText: {
    fontSize: 12,
    lineHeight: 1.5,
    color: '#334155',
  },
  lawyerBanner: {
    backgroundColor: '#FEF2F2',
    borderLeft: '4pt solid #EF4444',
    padding: 12,
    borderRadius: 4,
    marginBottom: 20,
  },
  lawyerTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: '#B91C1C',
    marginBottom: 4,
  },
  lawyerText: {
    fontSize: 10,
    color: '#7F1D1D',
    lineHeight: 1.4,
  },
  dateCard: {
    backgroundColor: '#FFFBEB',
    borderLeft: '4pt solid #D97706',
    padding: 10,
    borderRadius: 4,
    marginBottom: 10,
  },
  dateHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  dateType: {
    fontSize: 11,
    fontWeight: 700,
    color: '#B45309',
  },
  dateValue: {
    fontSize: 11,
    fontWeight: 700,
    color: '#0F172A',
  },
  dateDescription: {
    fontSize: 9,
    color: '#475569',
    lineHeight: 1.3,
  }
});

const getRiskColors = (score: number) => {
  if (score >= 7) return { bg: '#FEF2F2', border: '#FEE2E2', text: '#E24B4A' };
  if (score >= 4) return { bg: '#FEF3C7', border: '#FEEB8A', text: '#BA7517' };
  return { bg: '#ECFDF5', border: '#D1FAE5', text: '#639922' };
};

export const ReportDocument = ({ data, contractName, userPlan = 'free' }: { data: any, contractName: string, userPlan?: string }) => {
  const overallRisk = data.contract?.overallRisk ?? data.overallRiskScore ?? (data.overallRisk ? data.overallRisk * 10 : 0);
  
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{contractName}</Text>
          <Text style={styles.subtitle}>Risk Report generated by ClauseClaws AI</Text>
        </View>

        <View style={styles.summaryBox}>
          <Text style={{ fontSize: 16, fontWeight: 700, marginBottom: 8 }}>Executive Summary</Text>
          <Text style={styles.summaryText}>{data.contract?.summary || data.summary || ''}</Text>
          <Text style={{ marginTop: 10, fontSize: 14, fontWeight: 700 }}>
            Overall Risk Score: {overallRisk}/100
          </Text>
        </View>

        {data.contract?.requiresLawyerReview && (
          <View style={styles.lawyerBanner}>
            <Text style={styles.lawyerTitle}>⚠️ Legal Counsel Recommended</Text>
            <Text style={styles.lawyerText}>{data.contract.lawyerReferralReasoning}</Text>
          </View>
        )}

        {data.dates && data.dates.length > 0 && (
          <View style={styles.section} wrap={false}>
            <Text style={styles.sectionTitle}>Key Dates & Deadlines</Text>
            {data.dates.map((d: any, idx: number) => (
              <View key={idx} style={styles.dateCard}>
                <View style={styles.dateHeader}>
                  <Text style={styles.dateType}>{d.dateType}</Text>
                  <Text style={styles.dateValue}>
                    {d.dateValue ? new Date(d.dateValue).toLocaleDateString('en-US', { day: 'numeric', month: 'long', year: 'numeric' }) : 'Not specified'}
                  </Text>
                </View>
                {d.description && (
                  <Text style={styles.dateDescription}>{d.description}</Text>
                )}
              </View>
            ))}
          </View>
        )}

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Detailed Clause Analysis</Text>
          {data.clauses.map((c: any, i: number) => {
            const rColors = getRiskColors(c.riskScore);
            return (
              <View key={i} style={[styles.card, { borderLeft: `4pt solid ${rColors.text}` }]} wrap={false}>
                <View style={styles.cardHeader}>
                  <Text style={styles.clauseTitle}>{i + 1}. {c.clauseType} (Page {c.pageNumber || 'N/A'})</Text>
                  <View style={[styles.riskBadge, { backgroundColor: rColors.bg, borderColor: rColors.border }]}>
                    <Text style={[styles.riskBadgeText, { color: rColors.text }]}>RISK: {c.riskScore} / 10</Text>
                  </View>
                </View>

                {c.isPlaybookViolation && (
                  <View style={styles.playbookViolation}>
                    <Text style={styles.playbookText}>⚠️ Playbook Rule Violation Detected</Text>
                  </View>
                )}

                <Text style={styles.originalTextHeader}>Original Contract Language</Text>
                <Text style={styles.originalText}>{c.originalText}</Text>

                <Text style={styles.plainEnglishHeader}>Plain English Translation</Text>
                <Text style={styles.plainEnglish}>{c.plainEnglish}</Text>
                
                {c.negotiationTip && (
                  <>
                    <Text style={[styles.plainEnglishHeader, { color: '#D97706' }]}>Risk Exposure Tip</Text>
                    <Text style={styles.plainEnglish}>{c.negotiationTip}</Text>
                  </>
                )}
                
                {c.negotiationLanguage && (
                  userPlan === 'free' ? (
                    <View style={{ backgroundColor: '#F8FAFC', padding: 10, borderLeft: '4pt solid #94A3B8', marginTop: 10 }}>
                      <Text style={{ fontSize: 10, fontWeight: 700, color: '#64748B', marginBottom: 4 }}>Suggested Counter-Clause</Text>
                      <Text style={{ fontSize: 10, color: '#64748B' }}>[Upgrade to Starter or Growth tier to unlock AI-suggested counter-clauses]</Text>
                    </View>
                  ) : (
                    <View style={{ backgroundColor: '#F0FDF4', padding: 12, borderLeft: '4pt solid #16A34A', marginTop: 10 }}>
                      <Text style={{ fontSize: 10, fontWeight: 700, color: '#16A34A', marginBottom: 4 }}>Suggested Counter-Clause</Text>
                      <Text style={{ fontSize: 10, fontFamily: 'Courier', color: '#14532D' }}>{c.negotiationLanguage}</Text>
                    </View>
                  )
                )}
              </View>
            );
          })}
        </View>
      </Page>
    </Document>
  );
};

export const generatePdfBlob = async (data: any, contractName: string, userPlan: string = 'free') => {
  const blob = await pdf(<ReportDocument data={data} contractName={contractName} userPlan={userPlan} />).toBlob();
  return blob;
};
